### ISSUE TITLE
Unsafe eval in function constructor

### ISSUE THREAD

**Issue by anthony-arnold** [jeanlescure/short-unique-id#35]
[The ShortUniqueId constructor](https://github.com/jeanlescure/short-unique-id/blob/master/dist/short-unique-id.js#L144) contains some eval code.

Inheriting from Function and calling it's constructor violates strict Content-Security-Policy. The only way to use this library with CSP is to set `script-src: 'unsafe-eval'` which make CSP kind of useless.

Is there a way to remove this eval code without introducing a regression?

**Comment by jeanlescure** [comment]
Hi @anthony-arnold , thanks for the report!

I think the [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) object might be our best bet here to refactor that eval out of our code base.

I'll create a branch and test this out, only regression concern (off the top of my head) might be browser support.

I'll keep this issue updated as progress is done :+1:

**Comment by jeanlescure** [comment]
Hi @anthony-arnold, thanks for waiting this long, last night v3.0.5 was released, it should do away with the CSP warning you were getting and introduces no regression.

Cheers :beers:
