### ISSUE TITLE
is there a way to change the dictionary used to generate the ids?

### ISSUE THREAD

**Issue by MohGanji** [jeanlescure/short-unique-id#4]
I read the source code for that previous issue and found out that options is only used for debugging!
so is there any way I can give this module a string of characters and the library only uses this characters in generating random uids?

**Comment by jeanlescure** [comment]
Originally you could override the `dict` property, but V2 now lets you instantiate `ShortUniqueId` with a custom user-defined dictionary. For more info take a look at the README.

Cheers :)
