### ISSUE TITLE
Implement a "From UUID"

### ISSUE THREAD

**Issue by ctsstc** [jeanlescure/short-unique-id#54]
This would take a standard UUID and allow you to reduce it down to a smaller length by utilizing a larger base/dictionary. There would ideally be a way to revert a shortened UUID back to a full standard UUID as well. 

Given the new base/dictionary size there's a character limit to having the original information retained; it would be nice to know from a given dictionary what the size limitations are.

**Comment by jeanlescure** [comment]
Hi @ctsstc, thanks for your input.

This library does not rely on nor does it have relationship with standard UUID.

In any case, v5 was just released and has better dictionary handling functionality, you could try and implement the desired functionality on your codebase or on a library that extends short-unique-id's functionality.

Best regards 👍🏼 

Closing this issue as the requested feature is out of scope of this library's functional goals.
