### ISSUE TITLE
[NodeJS] ReferenceError: window is not defined

### ISSUE THREAD

**Issue by matiaslopezd** [jeanlescure/short-unique-id#6]
I want use in NodeJS but return that error: `ReferenceError: window is not defined`

I'm use the example in README.md

```js
// Import
var ShortUniqueId = require('short-unique-id');

// Instantiate
var uid = new ShortUniqueId();
```

For fix this temporarily I set `window` like global var but is bad practice.

**Comment by matiaslopezd** [comment]
Now I got new error `ShortUniqueId is not a constructor`.

The problem is with export because need use `ShortUniqueId.default()`. I recommend export with `module.export`.

**Comment by matiaslopezd** [comment]
Purpose solution to export error in:

https://github.com/jeanlescure/short-unique-id/blob/4b22731a32c6eaf52c20298e84288ac0d867d810/src/index.js#L136

```js
module.exports = ShortUniqueId;
```

Now I don't know where coming the `window` global var

**Comment by jeanlescure** [comment]
Was able to reproduce using [runkit for short-unique-id](https://npm.runkit.com/short-unique-id) using the following snippet:

```
const ShortUniqueId = require('short-unique-id');
const uid = new ShortUniqueId();
console.log(uid.randomUUID(6));
```

**Result:**

`ReferenceError: window is not defined`

**Comment by jeanlescure** [comment]
This is a [bug](https://github.com/webpack/webpack/issues/6677) related to Webpack 4.

Researching a [workaround](https://github.com/webpack/webpack/issues/6642#issuecomment-370222543) to stabilize `short-unique-id`/.

**Comment by jeanlescure** [comment]
Dev note, running `node` in repo root and then executing:

```
require('./dist/short-unique-id.min')
```

Will yield same `ReferenceError: window is not defined` output.

**Comment by jeanlescure** [comment]
@matiaslopezd Release [2.0.5](https://github.com/jeanlescure/short-unique-id/releases/tag/2.0.5) fixes this issue.

For future reference this was the change that fixed the error:

```javascript
// .neutrinorc.js

// before
    (neutrino) => {
      neutrino.config.output
        .filename(`${libName}.min.js`);
    },

// after
    (neutrino) => {
      neutrino.config.output
        .filename(`${libName}.min.js`)
        .set('globalObject', 'this'); // <= this line exchanges umd "window" object for "this"
    },

```

**Comment by matiaslopezd** [comment]
@jeanlescure Great thanks you!
